# .readthedocs.yaml
# Required: The version of the configuration file.
version: 2

# This section tells Read the Docs to skip its usual build steps.
# The 'build.jobs' key allows you to completely customize the build process.
build:
  os: ubuntu-lts-latest
  # The `jobs` key defines a list of commands to run.
  jobs:
    pre_build:
      - echo "execute prebuild jobs"
      - ls -al
      - echo "$READTHEDOCS_OUTPUT/html"
      - mv * $READTHEDOCS_OUTPUT/html

# This section defines the directory where the built artifacts are located.
# Read the Docs will publish the contents of this directory.
formats:
  - htmlzip
