# .readthedocs.yaml
# Required: The version of the configuration file.
version: 2

# This section tells Read the Docs to skip its usual build steps.
# The 'build.jobs' key allows you to completely customize the build process.
build:
  # The `jobs` key defines a list of commands to run.
  jobs:
    # Here, we run a single command that does nothing.
    # This effectively skips the default Sphinx or MkDocs build.
    - echo "Skipping standard build and using pre-built files"

# This section defines the directory where the built artifacts are located.
# Read the Docs will publish the contents of this directory.
formats:
  - htmlzip
