# .readthedocs.yaml
# see: https://docs.readthedocs.com/platform/stable/config-file/v2.html#build-jobs
# Required: The version of the configuration file.
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  commands:
    - echo "execute prebuild jobs, cwd is $(pwd)"
    - echo "$READTHEDOCS_OUTPUT and $(id)"
    - ls -al
    - tar --exclude-vcs -caf ../tmp/.tar . && \
      mkdir html && \
      tar -xavf ../tmp.tar -C html && \
      rm ../tmp.tar
    - echo "successfully release site to ${READTHEDOCS_OUTPUT}html"

# This section defines the directory where the built artifacts are located.
# Read the Docs will publish the contents of this directory.
formats:
  - htmlzip
