# .readthedocs.yaml
# see: https://docs.readthedocs.com/platform/stable/config-file/v2.html#build-jobs
# Required: The version of the configuration file.
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  commands:
    - echo "execute prebuild jobs, cwd is $(pwd)"
    - echo "$READTHEDOCS_OUTPUT and $(id)"
    - ls -al
    - tar --exclude-vcs -caf ../tmp.tar .
    - mkdir -p ${READTHEDOCS_OUTPUT}/html
    - tar -xavf ../tmp.tar -C ${READTHEDOCS_OUTPUT}/html
    - rm ../tmp.tar
    - |
      # 遍历当前目录及子目录中所有.html文件（排除index.html）
      find . -type f -name "*.html" ! -name "index.html" | while read -r file; do
        content='<meta http-equiv="Content-Type" content="text/html; charset=utf-8">'
        echo "$content" | sed -i "1i\\" - "$file"
        mv "$file" "${file%.html}" && echo "Renamed: $file → ${file%.html}"
      done
    - echo "successfully release site to ${READTHEDOCS_OUTPUT}html"

# This section defines the directory where the built artifacts are located.
# Read the Docs will publish the contents of this directory.
formats:
  - htmlzip
